# Generated by Django 3.0.3 on 2021-02-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0002_series_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='SeriesImage'),
        ),
    ]
