# Generated by Django 3.0.3 on 2020-09-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200903_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='saved_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
