# Generated by Django 3.0.3 on 2020-09-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_auto_20200905_1226'),
        ('Post', '0004_auto_20200904_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='Author.Author'),
        ),
    ]
