# Generated by Django 3.0.3 on 2020-09-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200906_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='author',
        ),
    ]
