# Generated by Django 3.0.3 on 2020-09-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_auto_20200906_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='imgslug',
            field=models.SlugField(default='', max_length=400),
        ),
    ]
