# Generated by Django 3.0.3 on 2021-01-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='CoverImage'),
        ),
    ]
