# Generated by Django 3.0.3 on 2021-01-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_auto_20210112_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='CoverImage'),
        ),
    ]
